# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 25a58a4a8238b014dbaa190b608e8caf3e239625faccee491b54391fc65df3a5002c6212fe2971fa7ebfa051e275c34789118ef6592864641abb670134a17efd

test:
  secret_key_base: a7be4350e761c59628aff73a193bf7cdc9a1babd923c54c221b32a1b2c6aa1958597555cc3d3745eb97038cd2f07b66e7e00ea8ded3e6fe393eb82a4eb0024ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
